-- Insert initial taste dictionary data
-- Dishes
INSERT INTO taste_dictionary (name, type) VALUES
-- Italian
('Pizza Margherita', 'dish'),
('Spaghetti Carbonara', 'dish'),
('Lasagna', 'dish'),
('Risotto', 'dish'),
('Osso Buco', 'dish'),
('Tiramisu', 'dish'),
('Bruschetta', 'dish'),
('Gnocchi', 'dish'),
('Parmigiana', 'dish'),
('Cannoli', 'dish'),
('Gelato', 'dish'),
('Prosciutto', 'dish'),

-- Japanese
('Sushi', 'dish'),
('Ramen', 'dish'),
('Tempura', 'dish'),
('Yakitori', 'dish'),
('Miso Soup', 'dish'),
('Sashimi', 'dish'),
('Udon', 'dish'),
('Donburi', 'dish'),
('Onigiri', 'dish'),
('Takoyaki', 'dish'),
('Okonomiyaki', 'dish'),
('Mochi', 'dish'),

-- Mexican
('Tacos', 'dish'),
('Burritos', 'dish'),
('Quesadillas', 'dish'),
('Guacamole', 'dish'),
('Enchiladas', 'dish'),
('Tamales', 'dish'),
('Nachos', 'dish'),
('Carnitas', 'dish'),
('Ceviche', 'dish'),
('Churros', 'dish'),
('Pozole', 'dish'),
('Mole', 'dish'),

-- Indian
('Curry', 'dish'),
('Biryani', 'dish'),
('Naan', 'dish'),
('Tandoori Chicken', 'dish'),
('Samosas', 'dish'),
('Dal', 'dish'),
('Butter Chicken', 'dish'),
('Palak Paneer', 'dish'),
('Masala Chai', 'dish'),
('Tikka Masala', 'dish'),
('Dosa', 'dish'),
('Idli', 'dish'),

-- Chinese
('Fried Rice', 'dish'),
('Dumplings', 'dish'),
('Kung Pao Chicken', 'dish'),
('Sweet and Sour Pork', 'dish'),
('Chow Mein', 'dish'),
('Peking Duck', 'dish'),
('Dim Sum', 'dish'),
('Mapo Tofu', 'dish'),
('Hot Pot', 'dish'),
('Spring Rolls', 'dish'),
('Wonton Soup', 'dish'),

-- American
('Hamburger', 'dish'),
('BBQ Ribs', 'dish'),
('Fried Chicken', 'dish'),
('Mac and Cheese', 'dish'),
('Apple Pie', 'dish'),
('Cheesecake', 'dish'),
('Buffalo Wings', 'dish'),
('Pancakes', 'dish'),
('Clam Chowder', 'dish'),
('Lobster Roll', 'dish'),

-- French
('Croissant', 'dish'),
('French Onion Soup', 'dish'),
('Coq au Vin', 'dish'),
('Ratatouille', 'dish'),
('Crème Brûlée', 'dish'),
('Bouillabaisse', 'dish'),
('Quiche', 'dish'),
('Escargot', 'dish'),
('Foie Gras', 'dish'),
('Macarons', 'dish'),

-- Thai
('Pad Thai', 'dish'),
('Tom Yum', 'dish'),
('Green Curry', 'dish'),
('Mango Sticky Rice', 'dish'),
('Som Tam', 'dish'),
('Massaman Curry', 'dish'),
('Thai Basil Chicken', 'dish'),
('Larb', 'dish'),
('Khao Pad', 'dish'),

-- Mediterranean/Middle Eastern
('Hummus', 'dish'),
('Falafel', 'dish'),
('Shawarma', 'dish'),
('Baklava', 'dish'),
('Tabbouleh', 'dish'),
('Kebab', 'dish'),
('Moussaka', 'dish'),
('Dolmas', 'dish'),
('Baba Ganoush', 'dish'),
('Pita Bread', 'dish'),

-- Korean
('Kimchi', 'dish'),
('Bulgogi', 'dish'),
('Bibimbap', 'dish'),
('Korean BBQ', 'dish'),
('Japchae', 'dish'),
('Tteokbokki', 'dish'),
('Galbi', 'dish'),
('Sundubu Jjigae', 'dish'),
('Kimchi Fried Rice', 'dish');

-- Ingredients
INSERT INTO taste_dictionary (name, type) VALUES
-- Proteins
('Chicken', 'ingredient'),
('Beef', 'ingredient'),
('Pork', 'ingredient'),
('Lamb', 'ingredient'),
('Fish', 'ingredient'),
('Salmon', 'ingredient'),
('Tuna', 'ingredient'),
('Shrimp', 'ingredient'),
('Crab', 'ingredient'),
('Lobster', 'ingredient'),
('Eggs', 'ingredient'),
('Tofu', 'ingredient'),
('Tempeh', 'ingredient'),
('Beans', 'ingredient'),
('Lentils', 'ingredient'),
('Chickpeas', 'ingredient'),

-- Vegetables
('Tomatoes', 'ingredient'),
('Onions', 'ingredient'),
('Garlic', 'ingredient'),
('Ginger', 'ingredient'),
('Bell Peppers', 'ingredient'),
('Carrots', 'ingredient'),
('Broccoli', 'ingredient'),
('Spinach', 'ingredient'),
('Kale', 'ingredient'),
('Lettuce', 'ingredient'),
('Cabbage', 'ingredient'),
('Mushrooms', 'ingredient'),
('Zucchini', 'ingredient'),
('Eggplant', 'ingredient'),
('Potatoes', 'ingredient'),
('Sweet Potatoes', 'ingredient'),
('Avocado', 'ingredient'),
('Cucumber', 'ingredient'),
('Celery', 'ingredient'),
('Asparagus', 'ingredient'),

-- Herbs & Spices
('Basil', 'ingredient'),
('Oregano', 'ingredient'),
('Thyme', 'ingredient'),
('Rosemary', 'ingredient'),
('Cilantro', 'ingredient'),
('Parsley', 'ingredient'),
('Mint', 'ingredient'),
('Black Pepper', 'ingredient'),
('Salt', 'ingredient'),
('Paprika', 'ingredient'),
('Cumin', 'ingredient'),
('Turmeric', 'ingredient'),
('Cinnamon', 'ingredient'),
('Cardamom', 'ingredient'),
('Bay Leaves', 'ingredient'),
('Saffron', 'ingredient'),
('Vanilla', 'ingredient'),
('Nutmeg', 'ingredient'),
('Cloves', 'ingredient'),
('Garam Masala', 'ingredient'),

-- Dairy & Cheese
('Mozzarella', 'ingredient'),
('Parmesan', 'ingredient'),
('Cheddar', 'ingredient'),
('Goat Cheese', 'ingredient'),
('Feta', 'ingredient'),
('Brie', 'ingredient'),
('Blue Cheese', 'ingredient'),
('Cream', 'ingredient'),
('Butter', 'ingredient'),
('Greek Yogurt', 'ingredient'),
('Milk', 'ingredient'),
('Heavy Cream', 'ingredient'),

-- Grains & Starches
('Rice', 'ingredient'),
('Quinoa', 'ingredient'),
('Pasta', 'ingredient'),
('Bread', 'ingredient'),
('Flour', 'ingredient'),
('Oats', 'ingredient'),
('Barley', 'ingredient'),
('Couscous', 'ingredient'),
('Bulgur', 'ingredient'),
('Polenta', 'ingredient'),
('Noodles', 'ingredient'),

-- Oils & Condiments
('Olive Oil', 'ingredient'),
('Sesame Oil', 'ingredient'),
('Coconut Oil', 'ingredient'),
('Soy Sauce', 'ingredient'),
('Fish Sauce', 'ingredient'),
('Vinegar', 'ingredient'),
('Lemon', 'ingredient'),
('Lime', 'ingredient'),
('Honey', 'ingredient'),
('Maple Syrup', 'ingredient'),
('Hot Sauce', 'ingredient'),
('Mustard', 'ingredient'),

-- Nuts & Seeds
('Almonds', 'ingredient'),
('Walnuts', 'ingredient'),
('Pecans', 'ingredient'),
('Cashews', 'ingredient'),
('Pine Nuts', 'ingredient'),
('Sesame Seeds', 'ingredient'),
('Chia Seeds', 'ingredient'),
('Flax Seeds', 'ingredient'),
('Sunflower Seeds', 'ingredient'),
('Pumpkin Seeds', 'ingredient'),

-- Premium/Specialty
('Truffle', 'ingredient'),
('Black Truffle', 'ingredient'),
('White Truffle', 'ingredient'),
('Caviar', 'ingredient'),
('Wagyu Beef', 'ingredient'),
('Uni', 'ingredient'),
('Foie Gras', 'ingredient'),
('Oysters', 'ingredient'),
('Scallops', 'ingredient'),
('Duck Confit', 'ingredient'),
('Prosciutto di Parma', 'ingredient')

ON CONFLICT (name) DO NOTHING;